tcp_ip:
    sub_port: "5555"
    req_port: "4444"
    zipcode: "00001"

udp_ip:
    port: "8080"
    send_group: "FV2"
    recv_group: "FV1"

socket:
    udpsend_flag: true
    udpsend_flag: true
    req_flag: true
    rep_falg: false
    sub_flag: true
    pub_flag: false
